[package]
name = "fornax-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fornax-types = { path = "../fornax-types" }
sqlx.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true
sha2.workspace = true

[dev-dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
